# Generated by Django 4.0.1 on 2024-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_yoga_pose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
