# Generated by Django 4.0.1 on 2024-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_yoga_pose', '0002_alter_chat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Experience',
            field=models.CharField(default='', max_length=100),
        ),
    ]
