# Generated by Django 4.0.1 on 2024-04-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_yoga_pose', '0003_trainer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=300),
        ),
    ]
