# Generated by Django 4.0.1 on 2024-05-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_yoga_pose', '0005_alter_complaint_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='Description',
            field=models.CharField(max_length=10000),
        ),
    ]
